/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bibliotecaa3;

// Imports devem vir AQUI, logo após o package!
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author edgle
 */
public class GestaoDeDevolucoesFrame extends javax.swing.JFrame {

    // === DADOS DE CONEXÃO ===
    private static final String URL  = "jdbc:mysql://localhost:3306/bibliotecaa3";
    private static final String USER = "root";
    private static final String PASS = "Fr4nc1sc0@";
    // =========================
     
    /**
     * Creates new form GestaoDeDevolucoesFrame
     */
    public GestaoDeDevolucoesFrame() {
        initComponents();
        carregarEmprestimos();
    }

    private void carregarEmprestimos() {
        DefaultTableModel model = (DefaultTableModel) tblEmprestimoCadastrado.getModel();
        model.setRowCount(0); // Limpa a tabela
        String sql = "SELECT ID, ID_Livro, ID_Membro, Data_Emprestimo, Data_Devolucao, Status FROM emprestimos";
        try (Connection conn = DriverManager.getConnection(URL, USER, PASS);
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getInt("ID"),
                    rs.getInt("ID_Livro"),
                    rs.getInt("ID_Membro"),
                    rs.getDate("Data_Emprestimo"),
                    rs.getDate("Data_Devolucao"),
                    rs.getString("Status")
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Erro ao carregar empréstimos:\n" + ex.getMessage(),
                "Erro de Conexão",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdLivro = new javax.swing.JTextField();
        dcDataDevolucao = new javax.swing.JFormattedTextField();
        btnRegistrarDevolucao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmprestimoCadastrado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTÃO DE DEVOLUÇÕES DE LIVROS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Data de Devolução :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Informe o ID do Livro");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        txtIdLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdLivro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        dcDataDevolucao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        dcDataDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnRegistrarDevolucao.setBackground(new java.awt.Color(102, 153, 0));
        btnRegistrarDevolucao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarDevolucao.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDevolucao.setText("Registrar Devolução");
        btnRegistrarDevolucao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        btnRegistrarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDevolucaoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tabela de empréstimos cadastrados");

        tblEmprestimoCadastrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        tblEmprestimoCadastrado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblEmprestimoCadastrado.setForeground(new java.awt.Color(0, 0, 153));
        tblEmprestimoCadastrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Livro", "Membro", "Data emprestimo", "Data devolução", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblEmprestimoCadastrado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dcDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnRegistrarDevolucao))
                            .addComponent(txtIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDevolucaoActionPerformed
        // TODO add your handling code here:
        
    // Lê o texto digitado no campo do ID e remove espaços extras
String sIdEmprestimo = txtIdLivro.getText().trim();
// Lê o texto digitado no campo da data de devolução
String dataDevStr = dcDataDevolucao.getText().trim();

// Verifica se algum campo está vazio
if (sIdEmprestimo.isEmpty() || dataDevStr.isEmpty()) {
    JOptionPane.showMessageDialog(this, 
        "Preencha todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
    return; // Interrompe a execução se algum campo estiver vazio
}

// Tenta converter o texto do ID para número inteiro
int id;
try {
    id = Integer.parseInt(sIdEmprestimo);
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, 
        "O ID deve ser um número inteiro.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
    return; // Interrompe se não for número válido
}

// Tenta converter o texto da data em um objeto Date usando o formato esperado
Date dataDev;
try {
    dataDev = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(dataDevStr);
} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, 
        "Data inválida! Use o formato dd/MM/yyyy", "Erro de Data", JOptionPane.ERROR_MESSAGE);
    return; // Interrompe se a data for inválida
}

// Monta o comando SQL para atualizar a devolução no banco
String sql = "UPDATE emprestimos SET Data_Devolucao = ?, Status = 'Devolvido' WHERE ID = ?";

// Abre conexão com o banco e executa o comando
try (Connection conn = DriverManager.getConnection(URL, USER, PASS);
     PreparedStatement ps = conn.prepareStatement(sql)) {

    // Preenche os parâmetros da query: 1 = data de devolução, 2 = ID do empréstimo
    ps.setDate(1, new java.sql.Date(dataDev.getTime()));
    ps.setInt(2, id);

    // Executa o update e verifica se alguma linha foi alterada
    int linhasAfetadas = ps.executeUpdate();
    if (linhasAfetadas > 0) {
        JOptionPane.showMessageDialog(this, 
            "Devolução registrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        // Limpa os campos do formulário
        txtIdLivro.setText("");
        dcDataDevolucao.setText("");
        // Atualiza a tabela exibida
        carregarEmprestimos();
    } else {
        JOptionPane.showMessageDialog(this, 
            "Nenhum empréstimo encontrado com o ID informado.", "Aviso", JOptionPane.WARNING_MESSAGE);
    }
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, 
        "Erro ao registrar devolução:\n" + ex.getMessage(), "Erro de Conexão", JOptionPane.ERROR_MESSAGE);
}

        
    }//GEN-LAST:event_btnRegistrarDevolucaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestaoDeDevolucoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestaoDeDevolucoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestaoDeDevolucoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestaoDeDevolucoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestaoDeDevolucoesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarDevolucao;
    private javax.swing.JFormattedTextField dcDataDevolucao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmprestimoCadastrado;
    private javax.swing.JTextField txtIdLivro;
    // End of variables declaration//GEN-END:variables
}
